version: '3'

services:
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1081:1080"
      - "1025:1025"
  db:
    image: mysql:5.7
    ports:
      - 3313:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
      - smtp
    build: .
    volumes:
      - ./work:/var/www/html
    ports:
      - "8002:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db_data:
